FROM gradle:6.8-jdk15 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
ENV GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx1024m"
RUN gradle bootJar --no-daemon

FROM openjdk:15-alpine
#RUN apk add --no-cache tzdata
#EXPOSE 8080
#RUN mkdir /app
#COPY --from=build /home/gradle/src/build/libs/*.jar /app/spring-boot-application.jar
#ENTRYPOINT ["java", "-jar", "/app/spring-boot-application.jar"]
COPY --from=build /home/gradle/src/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]