spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:6006/testdb"
    username: testdb
    password: testdb
